### PR TITLE
added mistake counter

### PR DESCRIPTION
**Pull request by khadnot**
Trying to get some practice with pull requests. I added a mistake counter to the app. Let me know what you think. Take care!

### CODE REVIEW

**Comment by khadnot** [comment]
@Cutecat42 did you see my pull request?

**Comment by Cutecat42** [comment]
I'm so sorry; I've been busy with starting a new job, selling my house, moving, etc. I'll look into it as soon as I can! :)

**Comment by khadnot** [comment]
No worries. You have alot going on right now. Take your time. Congrats on the new job!

**Review by Cutecat42 — APPROVED** [review]
This looks great. Thank you!

**Pull request merged**
